export default function CommonSentences() {
  const sentences = [
    { dutch: "Hallo", english: "Hello" },
    { dutch: "Goedemorgen", english: "Good morning" },
    { dutch: "Goedemiddag", english: "Good afternoon" },
    { dutch: "Goedenavond", english: "Good evening" },
    { dutch: "Welterusten", english: "Good night" },
    { dutch: "Hoe gaat het?", english: "How are you?" },
    { dutch: "Goed, dank je", english: "Good, thank you" },
    { dutch: "En met jou?", english: "And you?" },
    { dutch: "Tot ziens", english: "Goodbye" },
    { dutch: "Dag", english: "Bye" },
    { dutch: "Dank je wel", english: "Thank you" },
    { dutch: "Alsjeblieft", english: "Please / You're welcome" },
    { dutch: "Sorry", english: "Sorry" },
    { dutch: "Excuseer me", english: "Excuse me" },
    { dutch: "Ja", english: "Yes" },
    { dutch: "Nee", english: "No" },
    { dutch: "Misschien", english: "Maybe" },
    { dutch: "Ik begrijp het niet", english: "I don't understand" },
    { dutch: "Spreekt u Engels?", english: "Do you speak English?" },
    { dutch: "Ik spreek geen Nederlands", english: "I don't speak Dutch" },
    { dutch: "Hoe heet je?", english: "What's your name?" },
    { dutch: "Ik heet...", english: "My name is..." },
    { dutch: "Aangenaam", english: "Nice to meet you" },
    { dutch: "Waar kom je vandaan?", english: "Where are you from?" },
    { dutch: "Ik kom uit...", english: "I'm from..." },
    { dutch: "Waar woon je?", english: "Where do you live?" },
    { dutch: "Ik woon in...", english: "I live in..." },
    { dutch: "Hoe oud ben je?", english: "How old are you?" },
    { dutch: "Ik ben ... jaar oud", english: "I am ... years old" },
    { dutch: "Wat doe je?", english: "What do you do?" },
    { dutch: "Ik ben student", english: "I am a student" },
    { dutch: "Ik werk bij...", english: "I work at..." },
    { dutch: "Hoeveel kost dit?", english: "How much does this cost?" },
    { dutch: "Dat is te duur", english: "That's too expensive" },
    { dutch: "Kan ik met pinpas betalen?", english: "Can I pay with a card?" },
    { dutch: "Waar is het toilet?", english: "Where is the bathroom?" },
    { dutch: "Ik ben verdwaald", english: "I'm lost" },
    { dutch: "Kun je me helpen?", english: "Can you help me?" },
    { dutch: "Wat is dit?", english: "What is this?" },
    { dutch: "Wie is dat?", english: "Who is that?" },
    { dutch: "Wanneer?", english: "When?" },
    { dutch: "Waarom?", english: "Why?" },
    { dutch: "Hoe?", english: "How?" },
    { dutch: "Waar?", english: "Where?" },
    { dutch: "Ik heb honger", english: "I'm hungry" },
    { dutch: "Ik heb dorst", english: "I'm thirsty" },
    { dutch: "Ik ben moe", english: "I'm tired" },
    { dutch: "Ik ben ziek", english: "I'm sick" },
    { dutch: "Ik voel me goed", english: "I feel good" },
    { dutch: "Het spijt me", english: "I'm sorry" },
    { dutch: "Geen probleem", english: "No problem" },
    { dutch: "Natuurlijk", english: "Of course" },
    { dutch: "Ik weet het niet", english: "I don't know" },
    { dutch: "Dat is interessant", english: "That's interesting" },
    { dutch: "Wat leuk!", english: "How nice!" },
    { dutch: "Gefeliciteerd!", english: "Congratulations!" },
    { dutch: "Succes!", english: "Good luck!" },
    { dutch: "Veel plezier!", english: "Have fun!" },
    { dutch: "Smakelijk eten!", english: "Enjoy your meal!" },
    { dutch: "Proost!", english: "Cheers!" },
    { dutch: "Wat is je telefoonnummer?", english: "What's your phone number?" },
    { dutch: "Wat is je e-mailadres?", english: "What's your email address?" },
    { dutch: "Heb je een kaart?", english: "Do you have a map?" },
    { dutch: "Ik hou van Nederland", english: "I love the Netherlands" },
    { dutch: "Het weer is mooi vandaag", english: "The weather is nice today" },
    { dutch: "Het regent", english: "It's raining" },
    { dutch: "Het is koud", english: "It's cold" },
    { dutch: "Het is warm", english: "It's warm" },
    { dutch: "Hoe laat is het?", english: "What time is it?" },
    { dutch: "Het is drie uur", english: "It's three o'clock" },
    { dutch: "Tot morgen", english: "See you tomorrow" },
    { dutch: "Tot straks", english: "See you later" },
    { dutch: "Heb je tijd?", english: "Do you have time?" },
    { dutch: "Ik heb geen tijd", english: "I don't have time" },
    { dutch: "Een momentje", english: "One moment" },
    { dutch: "Wacht even", english: "Wait a moment" },
    { dutch: "Kom binnen", english: "Come in" },
    { dutch: "Ga zitten", english: "Sit down" },
    { dutch: "Wil je iets drinken?", english: "Would you like something to drink?" },
    { dutch: "Ja, graag", english: "Yes, please" },
    { dutch: "Nee, bedankt", english: "No, thank you" },
    { dutch: "Ik begrijp het", english: "I understand" },
    { dutch: "Kun je dat herhalen?", english: "Can you repeat that?" },
    { dutch: "Spreek langzamer alsjeblieft", english: "Speak slower please" },
    { dutch: "Wat betekent dit?", english: "What does this mean?" },
    { dutch: "Hoe schrijf je dat?", english: "How do you spell that?" },
    { dutch: "Ik leer Nederlands", english: "I'm learning Dutch" },
    { dutch: "Dat is moeilijk", english: "That's difficult" },
    { dutch: "Dat is makkelijk", english: "That's easy" },
    { dutch: "Ik ben gelukkig", english: "I'm happy" },
    { dutch: "Ik ben verdrietig", english: "I'm sad" },
    { dutch: "Ik ben boos", english: "I'm angry" },
    { dutch: "Ik ben blij", english: "I'm glad" },
    { dutch: "Dat is geweldig!", english: "That's great!" },
    { dutch: "Fantastisch!", english: "Fantastic!" },
    { dutch: "Wat jammer!", english: "What a pity!" },
    { dutch: "Maak je geen zorgen", english: "Don't worry" },
    { dutch: "Het geeft niet", english: "It doesn't matter" },
    { dutch: "Ik hou van je", english: "I love you" },
    { dutch: "Ik mis je", english: "I miss you" },
    { dutch: "Wat ben je aan het doen?", english: "What are you doing?" },
    { dutch: "Ik ben aan het werk", english: "I'm working" },
    { dutch: "Ik ben thuis", english: "I'm at home" },
    { dutch: "Waar ga je heen?", english: "Where are you going?" },
    { dutch: "Ik ga naar huis", english: "I'm going home" },
    { dutch: "Ik ga naar school", english: "I'm going to school" },
    { dutch: "Ik ga naar kantoor", english: "I'm going to the office" },
    { dutch: "Ik ga winkelen", english: "I'm going shopping" },
    { dutch: "Mag ik een bon?", english: "Can I have a receipt?" },
    { dutch: "Waar is de uitgang?", english: "Where is the exit?" },
    { dutch: "Waar is de ingang?", english: "Where is the entrance?" },
    { dutch: "Is dit de goede weg naar...?", english: "Is this the right way to...?" },
    { dutch: "Hoe ver is het?", english: "How far is it?" },
    { dutch: "Het is dichtbij", english: "It's nearby" },
    { dutch: "Het is ver weg", english: "It's far away" },
    { dutch: "Ga rechtdoor", english: "Go straight ahead" },
    { dutch: "Ga naar links", english: "Go left" },
    { dutch: "Ga naar rechts", english: "Go right" },
    { dutch: "Bij de hoek", english: "At the corner" },
    { dutch: "Bij het stoplicht", english: "At the traffic light" },
    { dutch: "Tegenover", english: "Opposite" },
    { dutch: "Naast", english: "Next to" },
    { dutch: "Tussen", english: "Between" },
    { dutch: "Achter", english: "Behind" },
    { dutch: "Voor", english: "In front of" },
    { dutch: "Boven", english: "Above / Upstairs" },
    { dutch: "Beneden", english: "Below / Downstairs" },
    { dutch: "Ik wil graag...", english: "I would like..." },
    { dutch: "Mag ik...?", english: "May I...?" },
    { dutch: "Kan ik...?", english: "Can I...?" },
    { dutch: "Heb je...?", english: "Do you have...?" },
    { dutch: "Ik heb geen...", english: "I don't have..." },
    { dutch: "Ik heb...", english: "I have..." },
    { dutch: "Ik wil...", english: "I want..." },
    { dutch: "Ik moet gaan", english: "I have to go" },
    { dutch: "Ik kan niet", english: "I can't" },
    { dutch: "Ik kan wel", english: "I can" },
    { dutch: "Dat klopt", english: "That's correct" },
    { dutch: "Dat klopt niet", english: "That's not correct" },
    { dutch: "Ben je zeker?", english: "Are you sure?" },
    { dutch: "Ik ben zeker", english: "I'm sure" },
    { dutch: "Ik denk het wel", english: "I think so" },
    { dutch: "Ik denk het niet", english: "I don't think so" },
    { dutch: "Ik hoop het", english: "I hope so" },
    { dutch: "Dat hoop ik niet", english: "I hope not" },
    { dutch: "Wat is er?", english: "What's wrong?" },
    { dutch: "Niets", english: "Nothing" },
    { dutch: "Alles is goed", english: "Everything is fine" },
    { dutch: "Er is een probleem", english: "There's a problem" },
    { dutch: "Kun je me verstaan?", english: "Can you hear me?" },
    { dutch: "Ik kan je niet verstaan", english: "I can't hear you" },
    { dutch: "Spreek je Nederlands?", english: "Do you speak Dutch?" },
    { dutch: "Een beetje", english: "A little bit" },
    { dutch: "Ik spreek een beetje Nederlands", english: "I speak a little Dutch" },
    { dutch: "Ik ben beginner", english: "I'm a beginner" },
    { dutch: "Wat is je favoriete...?", english: "What's your favorite...?" },
    { dutch: "Mijn favoriete kleur is...", english: "My favorite color is..." },
    { dutch: "Wat vind je ervan?", english: "What do you think of it?" },
    { dutch: "Ik vind het leuk", english: "I like it" },
    { dutch: "Ik vind het niet leuk", english: "I don't like it" },
    { dutch: "Ik hou van...", english: "I love..." },
    { dutch: "Ik hou niet van...", english: "I don't like..." },
    { dutch: "Wat zijn je hobbies?", english: "What are your hobbies?" },
    { dutch: "Ik hou van lezen", english: "I like reading" },
    { dutch: "Ik hou van muziek", english: "I like music" },
    { dutch: "Ik hou van sport", english: "I like sports" },
    { dutch: "Ik hou van reizen", english: "I like traveling" },
    { dutch: "Ik kook graag", english: "I like cooking" },
    { dutch: "Ik zwem graag", english: "I like swimming" },
    { dutch: "Waar is het station?", english: "Where is the train station?" },
    { dutch: "Waar is de bushalte?", english: "Where is the bus stop?" },
    { dutch: "Hoe kom ik bij...?", english: "How do I get to...?" },
    { dutch: "Welk perron?", english: "Which platform?" },
    { dutch: "Hoe laat vertrekt de trein?", english: "What time does the train leave?" },
    { dutch: "Hoe laat komt de bus?", english: "What time does the bus arrive?" },
    { dutch: "Een enkele reis", english: "A one-way ticket" },
    { dutch: "Een retour", english: "A return ticket" },
    { dutch: "Eerste klas", english: "First class" },
    { dutch: "Tweede klas", english: "Second class" },
    { dutch: "Ik wil graag reserveren", english: "I would like to make a reservation" },
    { dutch: "Is deze plaats vrij?", english: "Is this seat free?" },
    { dutch: "Deze plaats is bezet", english: "This seat is taken" },
    { dutch: "Mag ik langs?", english: "May I pass?" },
    { dutch: "Het is druk", english: "It's busy/crowded" },
    { dutch: "Er is veel verkeer", english: "There's a lot of traffic" },
    { dutch: "De trein heeft vertraging", english: "The train is delayed" },
    { dutch: "Ik heb een afspraak", english: "I have an appointment" },
    { dutch: "Ik ben te laat", english: "I'm late" },
    { dutch: "Ik ben op tijd", english: "I'm on time" },
    { dutch: "Ik ben vroeg", english: "I'm early" },
    { dutch: "Wacht op mij", english: "Wait for me" },
    { dutch: "Ik wacht op je", english: "I'm waiting for you" },
    { dutch: "Laten we gaan", english: "Let's go" },
    { dutch: "Kom mee", english: "Come with me" },
    { dutch: "Ik kom eraan", english: "I'm coming" },
    { dutch: "Doe voorzichtig", english: "Be careful" },
    { dutch: "Pas op!", english: "Watch out!" },
    { dutch: "Help!", english: "Help!" },
    { dutch: "Bel de politie", english: "Call the police" },
    { dutch: "Bel een ambulance", english: "Call an ambulance" },
    { dutch: "Er is een ongeluk", english: "There's an accident" },
    { dutch: "Ik heb pijn", english: "I'm in pain" },
    { dutch: "Mijn hoofd doet pijn", english: "My head hurts" },
    { dutch: "Mijn buik doet pijn", english: "My stomach hurts" },
    { dutch: "Ik heb koorts", english: "I have a fever" },
    { dutch: "Ik heb griep", english: "I have the flu" },
    { dutch: "Ik ben allergisch voor...", english: "I'm allergic to..." },
    { dutch: "Waar is de apotheek?", english: "Where is the pharmacy?" },
    { dutch: "Waar is het ziekenhuis?", english: "Where is the hospital?" },
    { dutch: "Ik heb een dokter nodig", english: "I need a doctor" },
    { dutch: "Ik heb medicijnen nodig", english: "I need medicine" },
    { dutch: "Heb je iets tegen hoofdpijn?", english: "Do you have something for headaches?" },
    { dutch: "Ik voel me beter", english: "I feel better" },
    { dutch: "Ik voel me slechter", english: "I feel worse" },
    { dutch: "Rust goed uit", english: "Rest well" },
    { dutch: "Beterschap!", english: "Get well soon!" },
    { dutch: "Waar kan ik eten?", english: "Where can I eat?" },
    { dutch: "Is er een restaurant in de buurt?", english: "Is there a restaurant nearby?" },
    { dutch: "Ik wil graag een tafel reserveren", english: "I would like to reserve a table" },
    { dutch: "Voor hoeveel personen?", english: "For how many people?" },
    { dutch: "Voor twee personen", english: "For two people" },
    { dutch: "Mag ik de menukaart?", english: "May I have the menu?" },
    { dutch: "Wat raad je aan?", english: "What do you recommend?" },
    { dutch: "Ik ben vegetariër", english: "I'm a vegetarian" },
    { dutch: "Ik ben veganist", english: "I'm a vegan" },
    { dutch: "Heeft dit vlees?", english: "Does this have meat?" },
    { dutch: "Heeft dit noten?", english: "Does this have nuts?" },
    { dutch: "Ik wil graag bestellen", english: "I would like to order" },
    { dutch: "Als voorgerecht", english: "As a starter" },
    { dutch: "Als hoofdgerecht", english: "As a main course" },
    { dutch: "Als nagerecht", english: "As dessert" },
    { dutch: "Wat wil je drinken?", english: "What would you like to drink?" },
    { dutch: "Een glas water", english: "A glass of water" },
    { dutch: "Een kopje koffie", english: "A cup of coffee" },
    { dutch: "Een kopje thee", english: "A cup of tea" },
    { dutch: "Een biertje", english: "A beer" },
    { dutch: "Een glas wijn", english: "A glass of wine" },
    { dutch: "Met of zonder ijs?", english: "With or without ice?" },
    { dutch: "Met melk en suiker", english: "With milk and sugar" },
    { dutch: "Zonder suiker", english: "Without sugar" },
    { dutch: "Het eten was heerlijk", english: "The food was delicious" },
    { dutch: "Het smaakt goed", english: "It tastes good" },
    { dutch: "Mag ik de rekening?", english: "May I have the bill?" },
    { dutch: "Mag ik afrekenen?", english: "May I pay?" },
    { dutch: "Is de bediening inbegrepen?", english: "Is service included?" },
    { dutch: "Hou het wisselgeld maar", english: "Keep the change" },
    { dutch: "Samen of apart betalen?", english: "Pay together or separately?" },
    { dutch: "Ik trakteer", english: "It's on me / My treat" },
    { dutch: "Laten we delen", english: "Let's split it" },
    { dutch: "Wat is de specialiteit hier?", english: "What's the specialty here?" },
    { dutch: "Is dit vers?", english: "Is this fresh?" },
    { dutch: "Kun je het opwarmen?", english: "Can you heat it up?" },
    { dutch: "Mag ik nog een beetje?", english: "May I have some more?" },
    { dutch: "Ik ben vol", english: "I'm full" },
    { dutch: "Het is genoeg", english: "It's enough" },
    { dutch: "Ik heb dorst", english: "I'm thirsty" },
    { dutch: "Waar kan ik boodschappen doen?", english: "Where can I do groceries?" },
    { dutch: "Waar is de supermarkt?", english: "Where is the supermarket?" },
    { dutch: "Hoe laat gaat de winkel open?", english: "What time does the store open?" },
    { dutch: "Hoe laat gaat de winkel dicht?", english: "What time does the store close?" },
    { dutch: "Is de winkel vandaag open?", english: "Is the store open today?" },
    { dutch: "Welke maat?", english: "What size?" },
    { dutch: "Welke kleur?", english: "What color?" },
    { dutch: "Mag ik dit passen?", english: "May I try this on?" },
    { dutch: "Waar is de paskamer?", english: "Where is the fitting room?" },
    { dutch: "Het past perfect", english: "It fits perfectly" },
    { dutch: "Het is te groot", english: "It's too big" },
    { dutch: "Het is te klein", english: "It's too small" },
    { dutch: "Heb je een kleinere maat?", english: "Do you have a smaller size?" },
    { dutch: "Heb je een grotere maat?", english: "Do you have a bigger size?" },
    { dutch: "Heb je andere kleuren?", english: "Do you have other colors?" },
    { dutch: "Ik neem dit", english: "I'll take this" },
    { dutch: "Ik denk er nog over na", english: "I'll think about it" },
    { dutch: "Mag ik een tasje?", english: "May I have a bag?" },
    { dutch: "Kan ik dit ruilen?", english: "Can I exchange this?" },
    { dutch: "Kan ik dit retourneren?", english: "Can I return this?" },
    { dutch: "Is er korting?", english: "Is there a discount?" },
    { dutch: "Is dit in de aanbieding?", english: "Is this on sale?" },
    { dutch: "Zijn jullie open op zondag?", english: "Are you open on Sunday?" },
    { dutch: "Wat is het adres?", english: "What's the address?" },
    { dutch: "Ik zoek een hotel", english: "I'm looking for a hotel" },
    { dutch: "Ik heb een kamer gereserveerd", english: "I have reserved a room" },
    { dutch: "Op naam van...", english: "Under the name of..." },
    { dutch: "Mag ik inchecken?", english: "May I check in?" },
    { dutch: "Mag ik uitchecken?", english: "May I check out?" },
    { dutch: "Wat is het wifi-wachtwoord?", english: "What's the wifi password?" },
    { dutch: "Is er wifi?", english: "Is there wifi?" },
    { dutch: "Wat is de kamerprijs?", english: "What's the room price?" },
    { dutch: "Is ontbijt inbegrepen?", english: "Is breakfast included?" },
    { dutch: "Hoe laat is het ontbijt?", english: "What time is breakfast?" },
    { dutch: "Kan ik mijn bagage hier laten?", english: "Can I leave my luggage here?" },
    { dutch: "Waar is de lift?", english: "Where is the elevator?" },
    { dutch: "Mag ik een andere kamer?", english: "May I have a different room?" },
    { dutch: "De airco werkt niet", english: "The air conditioning doesn't work" },
    { dutch: "De verwarming werkt niet", english: "The heating doesn't work" },
    { dutch: "Er is geen warm water", english: "There's no hot water" },
    { dutch: "Ik ben mijn sleutel kwijt", english: "I've lost my key" },
    { dutch: "Kun je me wakker maken om...?", english: "Can you wake me up at...?" },
    { dutch: "Is er roomservice?", english: "Is there room service?" },
    { dutch: "Ik ben leraar", english: "I'm a teacher" },
    { dutch: "Ik ben arts", english: "I'm a doctor" },
    { dutch: "Ik ben verpleegster", english: "I'm a nurse" },
    { dutch: "Ik ben ingenieur", english: "I'm an engineer" },
    { dutch: "Ik ben kok", english: "I'm a chef" },
    { dutch: "Ik ben schrijver", english: "I'm a writer" },
    { dutch: "Ik ben kunstenaar", english: "I'm an artist" },
    { dutch: "Ik ben musicus", english: "I'm a musician" },
    { dutch: "Ik werk thuis", english: "I work from home" },
    { dutch: "Ik ben werkloos", english: "I'm unemployed" },
    { dutch: "Ik ben met pensioen", english: "I'm retired" },
    { dutch: "Wat studeer je?", english: "What do you study?" },
    { dutch: "Ik studeer geneeskunde", english: "I study medicine" },
    { dutch: "Ik studeer economie", english: "I study economics" },
    { dutch: "Ik studeer informatica", english: "I study computer science" },
    { dutch: "Waar studeer je?", english: "Where do you study?" },
    { dutch: "Ik studeer aan de universiteit", english: "I study at the university" },
    { dutch: "In welk jaar zit je?", english: "What year are you in?" },
    { dutch: "Ik zit in mijn eerste jaar", english: "I'm in my first year" },
    { dutch: "Ik heb tentamens", english: "I have exams" },
    { dutch: "Ik heb vakantie", english: "I'm on vacation" },
    { dutch: "Wanneer begin je?", english: "When do you start?" },
    { dutch: "Wanneer ben je klaar?", english: "When are you finished?" },
    { dutch: "Dit is mijn vrouw", english: "This is my wife" },
    { dutch: "Dit is mijn man", english: "This is my husband" },
    { dutch: "Dit is mijn vriend", english: "This is my boyfriend" },
    { dutch: "Dit is mijn vriendin", english: "This is my girlfriend" },
    { dutch: "Dit zijn mijn ouders", english: "These are my parents" },
    { dutch: "Dit is mijn vader", english: "This is my father" },
    { dutch: "Dit is mijn moeder", english: "This is my mother" },
    { dutch: "Dit is mijn broer", english: "This is my brother" },
    { dutch: "Dit is mijn zus", english: "This is my sister" },
    { dutch: "Dit zijn mijn kinderen", english: "These are my children" },
    { dutch: "Dit is mijn zoon", english: "This is my son" },
    { dutch: "Dit is mijn dochter", english: "This is my daughter" },
    { dutch: "Dit is mijn opa", english: "This is my grandfather" },
    { dutch: "Dit is mijn oma", english: "This is my grandmother" },
    { dutch: "Ben je getrouwd?", english: "Are you married?" },
    { dutch: "Ik ben getrouwd", english: "I'm married" },
    { dutch: "Ik ben single", english: "I'm single" },
    { dutch: "Ik ben gescheiden", english: "I'm divorced" },
    { dutch: "Heb je kinderen?", english: "Do you have children?" },
    { dutch: "Ik heb twee kinderen", english: "I have two children" },
    { dutch: "Ik heb geen kinderen", english: "I don't have children" },
    { dutch: "Heb je huisdieren?", english: "Do you have pets?" },
    { dutch: "Ik heb een hond", english: "I have a dog" },
    { dutch: "Ik heb een kat", english: "I have a cat" },
    { dutch: "Wat is je telefoonnummer?", english: "What's your phone number?" },
    { dutch: "Kun je me bellen?", english: "Can you call me?" },
    { dutch: "Ik bel je later", english: "I'll call you later" },
    { dutch: "Stuur me een berichtje", english: "Send me a message" },
    { dutch: "Heb je WhatsApp?", english: "Do you have WhatsApp?" },
    { dutch: "Wat is je Instagram?", english: "What's your Instagram?" },
    { dutch: "Kunnen we vrienden worden?", english: "Can we be friends?" },
    { dutch: "Wat ben je aan het doen dit weekend?", english: "What are you doing this weekend?" },
    { dutch: "Zullen we afspreken?", english: "Shall we meet up?" },
    { dutch: "Wanneer kun je?", english: "When can you?" },
    { dutch: "Wat is een goede tijd voor jou?", english: "What's a good time for you?" },
    { dutch: "Waar zullen we afspreken?", english: "Where shall we meet?" },
    { dutch: "Tot dan!", english: "See you then!" },
    { dutch: "Ik verheug me erop", english: "I'm looking forward to it" },
    { dutch: "Het spijt me, ik kan niet", english: "I'm sorry, I can't" },
    { dutch: "Kunnen we het verzetten?", english: "Can we reschedule?" },
    { dutch: "Wat voor weer wordt het?", english: "What will the weather be like?" },
    { dutch: "Het is zonnig", english: "It's sunny" },
    { dutch: "Het is bewolkt", english: "It's cloudy" },
    { dutch: "Het sneeuwt", english: "It's snowing" },
    { dutch: "Het waait", english: "It's windy" },
    { dutch: "Er is storm", english: "There's a storm" },
    { dutch: "Het is mooi weer", english: "It's nice weather" },
    { dutch: "Het is slecht weer", english: "It's bad weather" },
    { dutch: "Welke temperatuur is het?", english: "What's the temperature?" },
    { dutch: "Het is tien graden", english: "It's ten degrees" },
    { dutch: "Het vriest", english: "It's freezing" },
    { dutch: "Ik heb het koud", english: "I'm cold" },
    { dutch: "Ik heb het warm", english: "I'm hot" },
    { dutch: "Neem een jas mee", english: "Take a jacket" },
    { dutch: "Vergeet je paraplu niet", english: "Don't forget your umbrella" },
    { dutch: "Wat is de datum vandaag?", english: "What's the date today?" },
    { dutch: "Welke dag is het?", english: "What day is it?" },
    { dutch: "Het is maandag", english: "It's Monday" },
    { dutch: "Het is dinsdag", english: "It's Tuesday" },
    { dutch: "Het is woensdag", english: "It's Wednesday" },
    { dutch: "Het is donderdag", english: "It's Thursday" },
    { dutch: "Het is vrijdag", english: "It's Friday" },
    { dutch: "Het is zaterdag", english: "It's Saturday" },
    { dutch: "Het is zondag", english: "It's Sunday" },
    { dutch: "Vandaag", english: "Today" },
    { dutch: "Morgen", english: "Tomorrow" },
    { dutch: "Gisteren", english: "Yesterday" },
    { dutch: "Deze week", english: "This week" },
    { dutch: "Volgende week", english: "Next week" },
    { dutch: "Vorige week", english: "Last week" },
    { dutch: "Deze maand", english: "This month" },
    { dutch: "Volgend jaar", english: "Next year" },
    { dutch: "Vorig jaar", english: "Last year" },
    { dutch: "Over een uur", english: "In an hour" },
    { dutch: "Over tien minuten", english: "In ten minutes" },
    { dutch: "Ik ben er over vijf minuten", english: "I'll be there in five minutes" },
    { dutch: "Hoe lang duurt het?", english: "How long does it take?" },
    { dutch: "Het duurt een uur", english: "It takes an hour" },
    { dutch: "Ben je klaar?", english: "Are you ready?" },
    { dutch: "Ik ben klaar", english: "I'm ready" },
    { dutch: "Ik ben bijna klaar", english: "I'm almost ready" },
    { dutch: "Nog niet", english: "Not yet" },
    { dutch: "Nu", english: "Now" },
    { dutch: "Later", english: "Later" },
    { dutch: "Straks", english: "Soon" },
    { dutch: "Meteen", english: "Right away" },
    { dutch: "Het is dringend", english: "It's urgent" },
    { dutch: "Het heeft geen haast", english: "There's no hurry" },
    { dutch: "Neem je tijd", english: "Take your time" },
    { dutch: "Schiet op!", english: "Hurry up!" },
    { dutch: "We hebben tijd genoeg", english: "We have enough time" },
    { dutch: "We moeten opschieten", english: "We need to hurry" },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white dark:from-gray-900 dark:to-gray-800 p-6">
      <div className="max-w-6xl mx-auto">
        <header className="text-center mb-12 pt-8">
          <h1 className="text-4xl md:text-5xl font-bold text-blue-600 dark:text-blue-400 mb-4">
            500 Common Dutch Sentences
          </h1>
          <p className="text-lg text-gray-600 dark:text-gray-300">
            Essential phrases for everyday conversations
          </p>
        </header>

        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-2">
          {sentences.map((sentence, index) => (
            <div
              key={index}
              className="bg-white dark:bg-gray-800 rounded-lg shadow-md hover:shadow-lg transition-shadow p-5 border border-gray-200 dark:border-gray-700"
            >
              <div className="flex items-start gap-3">
                <span className="flex-shrink-0 w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-bold">
                  {index + 1}
                </span>
                <div className="flex-1">
                  <p className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-2">
                    {sentence.dutch}
                  </p>
                  <p className="text-gray-600 dark:text-gray-400">
                    {sentence.english}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>

        <footer className="text-center mt-12 pb-8">
          <a
            href="/"
            className="inline-block bg-blue-600 hover:bg-blue-700 text-white font-semibold px-6 py-3 rounded-lg transition-colors"
          >
            ← Back to Home
          </a>
        </footer>
      </div>
    </div>
  );
}
